#!/bin/sh

/usr/bin/find /System/Library/Extensions/logKext.kext -exec /bin/chmod -R g-w {} \;
/sbin/kextload /System/Library/Extensions/logKext.kext
/Library/Application\ Support/logKext/logKextKeyGen
/bin/launchctl load /Library/LaunchDaemons/logKext.plist
/usr/bin/open /Library/Application\ Support/logKext/LogKext\ Readme.html
